// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _701_WebAPI.Data;

#nullable disable

namespace _701_WebAPI.Migrations
{
    [DbContext(typeof(_701_WebAPIContext))]
    [Migration("20220927134212_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_701_WebAPI.Models.ChargeCode", b =>
                {
                    b.Property<int>("ChargeCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargeCodeID"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChargeCodeID");

                    b.ToTable("ChargeCode");

                    b.HasData(
                        new
                        {
                            ChargeCodeID = 1,
                            Code = "7471",
                            Name = "Repairs & Maintenance"
                        },
                        new
                        {
                            ChargeCodeID = 2,
                            Code = "9891800",
                            Name = "Redevelopment"
                        },
                        new
                        {
                            ChargeCodeID = 3,
                            Code = "746211",
                            Name = "COAL BOILER"
                        },
                        new
                        {
                            ChargeCodeID = 4,
                            Code = "746212",
                            Name = "COAL FEED EQUIPMENT"
                        },
                        new
                        {
                            ChargeCodeID = 5,
                            Code = "746213",
                            Name = "DIESEL BOILER"
                        },
                        new
                        {
                            ChargeCodeID = 6,
                            Code = "746214",
                            Name = "STEAM BOILER"
                        },
                        new
                        {
                            ChargeCodeID = 7,
                            Code = "746215",
                            Name = "ELECTRIC BOILER"
                        },
                        new
                        {
                            ChargeCodeID = 8,
                            Code = "746221",
                            Name = "HEAT CIRCULATION PUMPS"
                        },
                        new
                        {
                            ChargeCodeID = 9,
                            Code = "746222",
                            Name = "HEATING MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 10,
                            Code = "746231",
                            Name = "VENTILATION - EXTRACTION"
                        },
                        new
                        {
                            ChargeCodeID = 11,
                            Code = "746232",
                            Name = "VENTILATION - AIR CIRCULATION"
                        },
                        new
                        {
                            ChargeCodeID = 12,
                            Code = "746241",
                            Name = "SWITCHBOARD MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 13,
                            Code = "746242",
                            Name = "LOAD SHEDDING EQUIPMENT"
                        },
                        new
                        {
                            ChargeCodeID = 14,
                            Code = "746243",
                            Name = "ALL APPLIANCE MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 15,
                            Code = "746244",
                            Name = "COMPUTER EQUIPMENT"
                        },
                        new
                        {
                            ChargeCodeID = 16,
                            Code = "746245",
                            Name = "RADIO AND TV ELECTRONIC"
                        },
                        new
                        {
                            ChargeCodeID = 17,
                            Code = "746246",
                            Name = "P.A.B.X and TELEPHONE"
                        },
                        new
                        {
                            ChargeCodeID = 18,
                            Code = "746247",
                            Name = "TILL MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 19,
                            Code = "746248",
                            Name = "LIGHT BULB COST"
                        },
                        new
                        {
                            ChargeCodeID = 20,
                            Code = "746249",
                            Name = "EMERGENCY GENERATOR COSTS"
                        },
                        new
                        {
                            ChargeCodeID = 21,
                            Code = "746251",
                            Name = "ROOM MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 22,
                            Code = "746252",
                            Name = "KITCHEN MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 23,
                            Code = "746253",
                            Name = "BAR MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 24,
                            Code = "746254",
                            Name = "BOTTLE STORE MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 25,
                            Code = "746255",
                            Name = "RESTAURANT MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 26,
                            Code = "746256",
                            Name = "EXTERIOR MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 27,
                            Code = "746257",
                            Name = "RECEPTION & FOYER MAINTENANCE "
                        },
                        new
                        {
                            ChargeCodeID = 28,
                            Code = "746258",
                            Name = "CONFERENCE ROOM MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 29,
                            Code = "746259",
                            Name = "MANAGER RESIDENCE MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 30,
                            Code = "746260",
                            Name = "SERVICE AREA MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 31,
                            Code = "746261",
                            Name = "KELVIN 7th FLOOR"
                        },
                        new
                        {
                            ChargeCodeID = 32,
                            Code = "746262",
                            Name = "SHOP MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 33,
                            Code = "746270",
                            Name = "REFRIGERATION LIQUOR"
                        },
                        new
                        {
                            ChargeCodeID = 34,
                            Code = "746271",
                            Name = "REFRIGERATION FOOD"
                        },
                        new
                        {
                            ChargeCodeID = 35,
                            Code = "746272",
                            Name = "CARPET & FLOOR CLEANING"
                        },
                        new
                        {
                            ChargeCodeID = 36,
                            Code = "746273",
                            Name = "SKIP BIN COSTS"
                        },
                        new
                        {
                            ChargeCodeID = 37,
                            Code = "746274",
                            Name = "PEST CONTROL"
                        },
                        new
                        {
                            ChargeCodeID = 38,
                            Code = "746275",
                            Name = "WINDOW CLEANING"
                        },
                        new
                        {
                            ChargeCodeID = 39,
                            Code = "746276",
                            Name = "BUILDING W.O.F."
                        },
                        new
                        {
                            ChargeCodeID = 40,
                            Code = "746277",
                            Name = "N.Z. FIRE SERVICE COSTS"
                        },
                        new
                        {
                            ChargeCodeID = 41,
                            Code = "746278",
                            Name = "LIFT MAINTENANCE"
                        },
                        new
                        {
                            ChargeCodeID = 42,
                            Code = "746279",
                            Name = "FIRE ALARM CALL OUTS"
                        },
                        new
                        {
                            ChargeCodeID = 43,
                            Code = "746280",
                            Name = "BEER LINE CLEANING"
                        },
                        new
                        {
                            ChargeCodeID = 44,
                            Code = "746281",
                            Name = "TOILET FLUSH VALVES"
                        },
                        new
                        {
                            ChargeCodeID = 45,
                            Code = "746291",
                            Name = "PROMOTIONAL"
                        },
                        new
                        {
                            ChargeCodeID = 46,
                            Code = "7685",
                            Name = "NON BUDGET COSTS"
                        },
                        new
                        {
                            ChargeCodeID = 47,
                            Code = "746296",
                            Name = "NURSERY COSTS - LAWNS"
                        },
                        new
                        {
                            ChargeCodeID = 48,
                            Code = "746297",
                            Name = "NURSERY COSTS - GARDENS"
                        },
                        new
                        {
                            ChargeCodeID = 49,
                            Code = "747500",
                            Name = "OTHER"
                        });
                });

            modelBuilder.Entity("_701_WebAPI.Models.Establishment", b =>
                {
                    b.Property<int>("EstablishmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstablishmentID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstablishmentID");

                    b.ToTable("Establishment");

                    b.HasData(
                        new
                        {
                            EstablishmentID = 1,
                            Address = "Corner of Tay Street & Racecourse Road",
                            Name = "Ascot Hotel Motel"
                        },
                        new
                        {
                            EstablishmentID = 2,
                            Address = "20 Kelvin Street",
                            Name = "Kelvin Hotel"
                        },
                        new
                        {
                            EstablishmentID = 3,
                            Address = "329 Dee Street",
                            Name = "Homestead Villa"
                        },
                        new
                        {
                            EstablishmentID = 4,
                            Address = "256 Tay Street",
                            Name = "Balmoral Lodge"
                        },
                        new
                        {
                            EstablishmentID = 5,
                            Address = "327 Tay Street",
                            Name = "Cable Court"
                        },
                        new
                        {
                            EstablishmentID = 6,
                            Address = "292 Dee Street",
                            Name = "Ashford Motor"
                        },
                        new
                        {
                            EstablishmentID = 7,
                            Address = "60 Glengarry Crescent",
                            Name = "Eastern Suburbs Tavern"
                        },
                        new
                        {
                            EstablishmentID = 8,
                            Address = "315 Centre Street",
                            Name = "Newfield Tavern"
                        },
                        new
                        {
                            EstablishmentID = 9,
                            Address = "Sydney Street",
                            Name = "Northern Tavern"
                        },
                        new
                        {
                            EstablishmentID = 10,
                            Address = "Dee Street",
                            Name = "Avenal Homestead"
                        },
                        new
                        {
                            EstablishmentID = 11,
                            Address = "181 North Road",
                            Name = "Waikiwi Tavern"
                        },
                        new
                        {
                            EstablishmentID = 12,
                            Address = "28 Cnr Dee & Leet Street",
                            Name = "Lone Star Cafe"
                        },
                        new
                        {
                            EstablishmentID = 13,
                            Address = "410 Elles Road",
                            Name = "Southland Tavern"
                        },
                        new
                        {
                            EstablishmentID = 14,
                            Address = "38 Dee Street",
                            Name = "Speights Alehouse"
                        },
                        new
                        {
                            EstablishmentID = 15,
                            Address = "90 Dee Street",
                            Name = "Waxys"
                        },
                        new
                        {
                            EstablishmentID = 16,
                            Address = "Cnr Elles Rd & Tweed Street",
                            Name = "South City Liquorland"
                        },
                        new
                        {
                            EstablishmentID = 17,
                            Address = "44 North Road",
                            Name = "Collingwood Super Liquor"
                        },
                        new
                        {
                            EstablishmentID = 18,
                            Address = "12 Bamborough Street",
                            Name = "East End Bottlestore"
                        },
                        new
                        {
                            EstablishmentID = 19,
                            Address = "8 Windsor Street",
                            Name = "Windsor Bottlestore"
                        },
                        new
                        {
                            EstablishmentID = 20,
                            Address = "406 Elles Road",
                            Name = "Southland Super Liquor"
                        },
                        new
                        {
                            EstablishmentID = 21,
                            Address = "35 East Road",
                            Name = "Ascot Sports Bar"
                        },
                        new
                        {
                            EstablishmentID = 22,
                            Address = "252 Dee Street",
                            Name = "Centrepoint Liquorland"
                        },
                        new
                        {
                            EstablishmentID = 23,
                            Address = "59 Dee Street",
                            Name = "The Langlands"
                        },
                        new
                        {
                            EstablishmentID = 24,
                            Address = "228 Elles Road",
                            Name = "Workshop Hours"
                        });
                });

            modelBuilder.Entity("_701_WebAPI.Models.EstablishmentCode", b =>
                {
                    b.Property<int>("EstablishmentCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstablishmentCodeID"), 1L, 1);

                    b.Property<int>("ChargeCodeID")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentID")
                        .HasColumnType("int");

                    b.HasKey("EstablishmentCodeID");

                    b.ToTable("EstablishmentCode");

                    b.HasData(
                        new
                        {
                            EstablishmentCodeID = 1,
                            ChargeCodeID = 1,
                            EstablishmentID = 1
                        },
                        new
                        {
                            EstablishmentCodeID = 2,
                            ChargeCodeID = 2,
                            EstablishmentID = 1
                        },
                        new
                        {
                            EstablishmentCodeID = 3,
                            ChargeCodeID = 43,
                            EstablishmentID = 1
                        },
                        new
                        {
                            EstablishmentCodeID = 4,
                            ChargeCodeID = 48,
                            EstablishmentID = 1
                        },
                        new
                        {
                            EstablishmentCodeID = 5,
                            ChargeCodeID = 1,
                            EstablishmentID = 23
                        },
                        new
                        {
                            EstablishmentCodeID = 6,
                            ChargeCodeID = 2,
                            EstablishmentID = 23
                        },
                        new
                        {
                            EstablishmentCodeID = 7,
                            ChargeCodeID = 43,
                            EstablishmentID = 23
                        },
                        new
                        {
                            EstablishmentCodeID = 8,
                            ChargeCodeID = 1,
                            EstablishmentID = 2
                        },
                        new
                        {
                            EstablishmentCodeID = 9,
                            ChargeCodeID = 2,
                            EstablishmentID = 2
                        },
                        new
                        {
                            EstablishmentCodeID = 10,
                            ChargeCodeID = 43,
                            EstablishmentID = 2
                        },
                        new
                        {
                            EstablishmentCodeID = 11,
                            ChargeCodeID = 1,
                            EstablishmentID = 3
                        },
                        new
                        {
                            EstablishmentCodeID = 12,
                            ChargeCodeID = 2,
                            EstablishmentID = 3
                        },
                        new
                        {
                            EstablishmentCodeID = 13,
                            ChargeCodeID = 1,
                            EstablishmentID = 4
                        },
                        new
                        {
                            EstablishmentCodeID = 14,
                            ChargeCodeID = 2,
                            EstablishmentID = 4
                        },
                        new
                        {
                            EstablishmentCodeID = 15,
                            ChargeCodeID = 1,
                            EstablishmentID = 5
                        },
                        new
                        {
                            EstablishmentCodeID = 16,
                            ChargeCodeID = 2,
                            EstablishmentID = 5
                        },
                        new
                        {
                            EstablishmentCodeID = 17,
                            ChargeCodeID = 1,
                            EstablishmentID = 6
                        },
                        new
                        {
                            EstablishmentCodeID = 18,
                            ChargeCodeID = 2,
                            EstablishmentID = 6
                        },
                        new
                        {
                            EstablishmentCodeID = 19,
                            ChargeCodeID = 1,
                            EstablishmentID = 7
                        },
                        new
                        {
                            EstablishmentCodeID = 20,
                            ChargeCodeID = 2,
                            EstablishmentID = 7
                        },
                        new
                        {
                            EstablishmentCodeID = 21,
                            ChargeCodeID = 43,
                            EstablishmentID = 7
                        },
                        new
                        {
                            EstablishmentCodeID = 22,
                            ChargeCodeID = 1,
                            EstablishmentID = 8
                        },
                        new
                        {
                            EstablishmentCodeID = 23,
                            ChargeCodeID = 2,
                            EstablishmentID = 8
                        },
                        new
                        {
                            EstablishmentCodeID = 24,
                            ChargeCodeID = 43,
                            EstablishmentID = 8
                        },
                        new
                        {
                            EstablishmentCodeID = 25,
                            ChargeCodeID = 1,
                            EstablishmentID = 9
                        },
                        new
                        {
                            EstablishmentCodeID = 26,
                            ChargeCodeID = 2,
                            EstablishmentID = 9
                        },
                        new
                        {
                            EstablishmentCodeID = 27,
                            ChargeCodeID = 43,
                            EstablishmentID = 9
                        },
                        new
                        {
                            EstablishmentCodeID = 28,
                            ChargeCodeID = 1,
                            EstablishmentID = 10
                        },
                        new
                        {
                            EstablishmentCodeID = 29,
                            ChargeCodeID = 2,
                            EstablishmentID = 10
                        },
                        new
                        {
                            EstablishmentCodeID = 30,
                            ChargeCodeID = 43,
                            EstablishmentID = 10
                        },
                        new
                        {
                            EstablishmentCodeID = 31,
                            ChargeCodeID = 1,
                            EstablishmentID = 11
                        },
                        new
                        {
                            EstablishmentCodeID = 32,
                            ChargeCodeID = 2,
                            EstablishmentID = 11
                        },
                        new
                        {
                            EstablishmentCodeID = 33,
                            ChargeCodeID = 43,
                            EstablishmentID = 11
                        },
                        new
                        {
                            EstablishmentCodeID = 34,
                            ChargeCodeID = 1,
                            EstablishmentID = 12
                        },
                        new
                        {
                            EstablishmentCodeID = 35,
                            ChargeCodeID = 2,
                            EstablishmentID = 12
                        },
                        new
                        {
                            EstablishmentCodeID = 36,
                            ChargeCodeID = 43,
                            EstablishmentID = 12
                        },
                        new
                        {
                            EstablishmentCodeID = 37,
                            ChargeCodeID = 1,
                            EstablishmentID = 13
                        },
                        new
                        {
                            EstablishmentCodeID = 38,
                            ChargeCodeID = 2,
                            EstablishmentID = 13
                        },
                        new
                        {
                            EstablishmentCodeID = 39,
                            ChargeCodeID = 43,
                            EstablishmentID = 13
                        },
                        new
                        {
                            EstablishmentCodeID = 40,
                            ChargeCodeID = 1,
                            EstablishmentID = 14
                        },
                        new
                        {
                            EstablishmentCodeID = 41,
                            ChargeCodeID = 2,
                            EstablishmentID = 14
                        },
                        new
                        {
                            EstablishmentCodeID = 42,
                            ChargeCodeID = 43,
                            EstablishmentID = 14
                        },
                        new
                        {
                            EstablishmentCodeID = 43,
                            ChargeCodeID = 1,
                            EstablishmentID = 15
                        },
                        new
                        {
                            EstablishmentCodeID = 44,
                            ChargeCodeID = 2,
                            EstablishmentID = 15
                        },
                        new
                        {
                            EstablishmentCodeID = 45,
                            ChargeCodeID = 43,
                            EstablishmentID = 15
                        },
                        new
                        {
                            EstablishmentCodeID = 46,
                            ChargeCodeID = 1,
                            EstablishmentID = 22
                        },
                        new
                        {
                            EstablishmentCodeID = 47,
                            ChargeCodeID = 2,
                            EstablishmentID = 22
                        },
                        new
                        {
                            EstablishmentCodeID = 48,
                            ChargeCodeID = 43,
                            EstablishmentID = 22
                        },
                        new
                        {
                            EstablishmentCodeID = 49,
                            ChargeCodeID = 1,
                            EstablishmentID = 16
                        },
                        new
                        {
                            EstablishmentCodeID = 50,
                            ChargeCodeID = 2,
                            EstablishmentID = 16
                        },
                        new
                        {
                            EstablishmentCodeID = 51,
                            ChargeCodeID = 43,
                            EstablishmentID = 16
                        },
                        new
                        {
                            EstablishmentCodeID = 52,
                            ChargeCodeID = 1,
                            EstablishmentID = 17
                        },
                        new
                        {
                            EstablishmentCodeID = 53,
                            ChargeCodeID = 2,
                            EstablishmentID = 17
                        },
                        new
                        {
                            EstablishmentCodeID = 54,
                            ChargeCodeID = 43,
                            EstablishmentID = 17
                        },
                        new
                        {
                            EstablishmentCodeID = 55,
                            ChargeCodeID = 1,
                            EstablishmentID = 18
                        },
                        new
                        {
                            EstablishmentCodeID = 56,
                            ChargeCodeID = 2,
                            EstablishmentID = 18
                        },
                        new
                        {
                            EstablishmentCodeID = 57,
                            ChargeCodeID = 43,
                            EstablishmentID = 18
                        },
                        new
                        {
                            EstablishmentCodeID = 58,
                            ChargeCodeID = 1,
                            EstablishmentID = 19
                        },
                        new
                        {
                            EstablishmentCodeID = 59,
                            ChargeCodeID = 2,
                            EstablishmentID = 19
                        },
                        new
                        {
                            EstablishmentCodeID = 60,
                            ChargeCodeID = 1,
                            EstablishmentID = 20
                        },
                        new
                        {
                            EstablishmentCodeID = 61,
                            ChargeCodeID = 2,
                            EstablishmentID = 20
                        },
                        new
                        {
                            EstablishmentCodeID = 62,
                            ChargeCodeID = 43,
                            EstablishmentID = 20
                        },
                        new
                        {
                            EstablishmentCodeID = 63,
                            ChargeCodeID = 1,
                            EstablishmentID = 20
                        },
                        new
                        {
                            EstablishmentCodeID = 64,
                            ChargeCodeID = 2,
                            EstablishmentID = 20
                        },
                        new
                        {
                            EstablishmentCodeID = 65,
                            ChargeCodeID = 1,
                            EstablishmentID = 21
                        },
                        new
                        {
                            EstablishmentCodeID = 66,
                            ChargeCodeID = 2,
                            EstablishmentID = 21
                        },
                        new
                        {
                            EstablishmentCodeID = 67,
                            ChargeCodeID = 49,
                            EstablishmentID = 24
                        });
                });

            modelBuilder.Entity("_701_WebAPI.Models.FinancialPeriod", b =>
                {
                    b.Property<int>("FinancialPeriodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialPeriodID"), 1L, 1);

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weeks")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("FinancialPeriodID");

                    b.ToTable("FinancialPeriod");

                    b.HasData(
                        new
                        {
                            FinancialPeriodID = 1,
                            EndDate = "05/01/2022 00:00",
                            Month = "April",
                            StartDate = "03/27/2022 00:00",
                            Weeks = 5,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 2,
                            EndDate = "05/29/2022 00:00",
                            Month = "May",
                            StartDate = "05/01/2022 00:00",
                            Weeks = 4,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 3,
                            EndDate = "06/26/2022 00:00",
                            Month = "June",
                            StartDate = "05/29/2022 00:00",
                            Weeks = 4,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 4,
                            EndDate = "07/31/2022 00:00",
                            Month = "July",
                            StartDate = "06/26/2022 00:00",
                            Weeks = 5,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 5,
                            EndDate = "08/28/2022 00:00",
                            Month = "August",
                            StartDate = "07/31/2022 00:00",
                            Weeks = 4,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 6,
                            EndDate = "10/02/2022 00:00",
                            Month = "September",
                            StartDate = "08/28/2022 00:00",
                            Weeks = 5,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 7,
                            EndDate = "10/30/2022 00:00",
                            Month = "October",
                            StartDate = "10/02/2022 00:00",
                            Weeks = 4,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 8,
                            EndDate = "11/27/2022 00:00",
                            Month = "November",
                            StartDate = "10/30/2022 00:00",
                            Weeks = 4,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 9,
                            EndDate = "01/01/2023 00:00",
                            Month = "December",
                            StartDate = "11/27/2022 00:00",
                            Weeks = 5,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 10,
                            EndDate = "01/29/2023 00:00",
                            Month = "January",
                            StartDate = "01/01/2023 00:00",
                            Weeks = 4,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 11,
                            EndDate = "02/26/2023 00:00",
                            Month = "February",
                            StartDate = "01/29/2023 00:00",
                            Weeks = 4,
                            Year = 2022
                        },
                        new
                        {
                            FinancialPeriodID = 12,
                            EndDate = "04/02/2023 00:00",
                            Month = "March",
                            StartDate = "02/26/2023 00:00",
                            Weeks = 4,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("_701_WebAPI.Models.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"), 1L, 1);

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChargeCodeID")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentID")
                        .HasColumnType("int");

                    b.Property<int?>("FinancialPeriodID")
                        .HasColumnType("int");

                    b.Property<string>("FinishTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hours")
                        .HasColumnType("float");

                    b.Property<double?>("HoursOT")
                        .HasColumnType("float");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobID");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            JobID = 1,
                            AccountID = "auth0|6332c7bb35450ad949086866",
                            ChargeCodeID = 1,
                            EstablishmentID = 16,
                            FinancialPeriodID = 6,
                            FinishTime = "08/29/2022 10:45",
                            Hours = 5.25,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Just started painting the entirety of south city liquorland",
                            StartTime = "08/29/2022 05:30"
                        },
                        new
                        {
                            JobID = 2,
                            AccountID = "auth0|6332c7bb35450ad949086866",
                            ChargeCodeID = 1,
                            EstablishmentID = 16,
                            FinancialPeriodID = 6,
                            FinishTime = "08/29/2022 17:00",
                            Hours = 4.0,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Continued painting the entirety of south city liquorland",
                            StartTime = "08/29/2022 13:00"
                        },
                        new
                        {
                            JobID = 3,
                            AccountID = "auth0|6332c7bb35450ad949086866",
                            ChargeCodeID = 1,
                            EstablishmentID = 16,
                            FinancialPeriodID = 6,
                            FinishTime = "09/15/2023 12:45",
                            Hours = 6.75,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Continued painting the entirety of south city liquorland",
                            StartTime = "09/15/2022 06:00"
                        },
                        new
                        {
                            JobID = 4,
                            AccountID = "auth0|6332c7bb35450ad949086866",
                            ChargeCodeID = 1,
                            EstablishmentID = 16,
                            FinancialPeriodID = 6,
                            FinishTime = "09/17/2022 09:00",
                            Hours = 3.0,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Just finished painting the entirety of south city liquorland by myself",
                            StartTime = "09/17/2022 06:00"
                        },
                        new
                        {
                            JobID = 5,
                            AccountID = "auth0|2",
                            ChargeCodeID = 2,
                            EstablishmentID = 15,
                            FinancialPeriodID = 4,
                            FinishTime = "06/13/2022 13:00",
                            Hours = 8.0,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Just finished building some chairs for waxys",
                            StartTime = "06/13/2022 05:00"
                        },
                        new
                        {
                            JobID = 6,
                            AccountID = "auth0|2",
                            ChargeCodeID = 2,
                            EstablishmentID = 15,
                            FinancialPeriodID = 4,
                            FinishTime = "06/14/2022 10:00",
                            Hours = 5.0,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Just started building some tables for waxys",
                            StartTime = "06/14/2022 05:00"
                        },
                        new
                        {
                            JobID = 7,
                            AccountID = "auth0|2",
                            ChargeCodeID = 2,
                            EstablishmentID = 15,
                            FinancialPeriodID = 4,
                            FinishTime = "06/15/2022 11:00",
                            Hours = 3.5,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Just finished building some tables for waxys",
                            StartTime = "06/15/2022 07:30"
                        },
                        new
                        {
                            JobID = 8,
                            AccountID = "auth0|3",
                            ChargeCodeID = 1,
                            EstablishmentID = 1,
                            FinancialPeriodID = 10,
                            FinishTime = "01/04/2023 13:00",
                            Hours = 7.5,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Did some plumbing out at the ascot",
                            StartTime = "01/04/2023 05:30"
                        },
                        new
                        {
                            JobID = 9,
                            AccountID = "auth0|3",
                            ChargeCodeID = 1,
                            EstablishmentID = 1,
                            FinancialPeriodID = 10,
                            FinishTime = "01/06/2023 13:00",
                            Hours = 8.0,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Did some plumbing out at the ascot, a pipe under the sink was leaking",
                            StartTime = "01/06/2023 05:00"
                        },
                        new
                        {
                            JobID = 10,
                            AccountID = "auth0|6",
                            ChargeCodeID = 1,
                            EstablishmentID = 11,
                            FinancialPeriodID = 3,
                            FinishTime = "06/16/2022 18:00",
                            Hours = 5.0,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Started some wiring out at the kiwi",
                            StartTime = "06/16/2022 13:00"
                        },
                        new
                        {
                            JobID = 11,
                            AccountID = "auth0|6",
                            ChargeCodeID = 1,
                            EstablishmentID = 11,
                            FinancialPeriodID = 3,
                            FinishTime = "06/18/2022 17:00",
                            Hours = 5.0,
                            HoursOT = 0.0,
                            IsCompleted = true,
                            Notes = "Finished the wiring out at the kiwi",
                            StartTime = "06/18/2022 12:00"
                        });
                });

            modelBuilder.Entity("_701_WebAPI.Models.Trade", b =>
                {
                    b.Property<int>("TradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeID"), 1L, 1);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TradeID");

                    b.ToTable("Trade");

                    b.HasData(
                        new
                        {
                            TradeID = 1,
                            Type = "Painter"
                        },
                        new
                        {
                            TradeID = 2,
                            Type = "Carpenter"
                        },
                        new
                        {
                            TradeID = 3,
                            Type = "Plumber"
                        },
                        new
                        {
                            TradeID = 4,
                            Type = "Beer Serviceman"
                        },
                        new
                        {
                            TradeID = 5,
                            Type = "Electrican"
                        },
                        new
                        {
                            TradeID = 6,
                            Type = "Gardener"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
